# Generated by Django 5.0.7 on 2024-08-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('price', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
