# Generated by Django 5.0.7 on 2024-08-06 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
